config/routes.rb
Rails.application.routes.draw do
 
  root 'static_pages#home'
  get '/contact',          to: 'messages#new', as: 'new_message'
  post '/contact',         to: 'messages#create', as: 'create_message'
  
  get '/test', to: 'static_pages#test'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
    include ActiveModel::Model
    attr_accessor :name, :email, :content
    validates :content, presence: true
    validates :name,  presence: true, length: { maximum: 50 }
    EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 245 },
                      format: { with: EMAIL_REGEX }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :detect_device_variant
  
  private
    
  def detect_device_variant
    request.variant = :phone if browser.device.mobile?
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    def new
        @message = Message.new
    end
    
    def create
    @message = Message.new message_params

        if @message.valid?
            ContactMailer.contact_me(@message).deliver_now
            flash[:info] = "Thank you for your message!" 
            redirect_to root_path 
        else
            render :new
        end
    end

  private

  def message_params
    params.require(:message).permit(:name, :email, :content)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def home
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
    # Returns title of page
    def full_title(page_title = '')
        base_title = "Social Curation"
        if page_title.empty?
            base_title
        else
            base_title + " | " + page_title
        end
    end

end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_application_layout.html.erb
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <% #debug(params) if Rails.env.development? %>
    </div>

app/views/layouts/_footer.html.erb
<footer class="footer navbar-static-bottom">
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-default navbar-static-top">
    <div class="container">
        <%= link_to "Social Curation", root_path, method: :get, id: "logo" %>
    </div>
    <br>
    <div class="container-center">
        <nav>
            <ul class="nav navbar-nav">
                <li><%= link_to "Services", services_path, id: "logo-three" %></li>
                <li><%= link_to "Create Your Profile", new_message_path, id: "logo-two" %></li>
                <li><%= link_to "Pricing & About", about_path, id: "logo-three" %></li>
            </ul>
        </nav>
    </div>
</header>

app/views/layouts/_menu.html.erb
<div class="menu-header" onclick="openNav()">Menu</div>

<div id="mySidenav" class="sidenav">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
      <%= link_to "Create Your Profile", new_message_path, id: "logo-four-phone" %>
      <%= link_to "Services", services_path, id: "logo-four-phone" %>
      <%= link_to "Pricing & About", about_path, id: "logo-four-phone" %>
</div>

<script>
function openNav() {
    document.getElementById("mySidenav").style.width = "250px";
    document.body.style.backgroundColor = "rgba(0,0,0,0.4)";
}

function closeNav() {
    document.getElementById("mySidenav").style.width = "0";
    document.body.style.backgroundColor = "white";
}
</script>

app/views/layouts/_phone_header.html.erb
<header class="navbar navbar-default navbar-static-top">
    <div class="container">
            <%= render 'layouts/menu' %>
    </div>
    <br>
    <div class="container-center">
        <%= link_to "Social Curation", root_path, method: :get, id: "logo" %>
    </body>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 
                                'data-turbolinks-track': 'reload'%>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
<![endif]-->

app/views/layouts/application.html+phone.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
      <%= favicon_link_tag 'favicon.ico' %>
      <%= render 'layouts/rails_default' %>
      <%= render 'layouts/shim' %>
      
  </head>
    <body id="phone-body">
    <%= render 'layouts/application_layout' %>
    <%= yield %>

  </body>
</html>



<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
      <%= favicon_link_tag 'favicon.ico' %>
      <%= render 'layouts/rails_default' %>
      <%= render 'layouts/shim' %>
  </head>
  <body>
    <div id="skrollr-body">
        <%= render 'layouts/application_layout' %>
        <%= yield %>
   
      <script type="text/javascript">
      $(function(){
        skrollr.init({forceHeight: false});
      });
      </script>   
	  
	  </div>
  </body>
</html>

<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">

app/views/messages/_new.html+phone.erb
<% @message = Message.new %>
  <div class="col-sm-6 col-centered">
    <h5>Interested in any of our services?</h5> 
    <h5>Have questions about what we do?</h5> 
    <h5>Don't hesitate to contact us!</h5>
    &nbsp;
    <%= form_for @message, url: create_message_url do |f| %>
      <%= notice %>
      <%= @message.errors.full_messages.join(', ') %>

      <%= f.text_field :name, placeholder: 'name' %>
      <%= f.email_field :email, placeholder: 'email' %>
      <%= f.text_area :content, placeholder: 'message' %>
      <%= f.submit 'Send' %>
    <% end %>
    &nbsp;
    <p class="tiny">*Fake accounts will not be made to impersonate existing people. Fake accounts may not be used to harrass anyone in any way. Failure to comply with these rules and all rules outlined in our contracts and/or about page will result in termination of your service(s) and/or contract(s). By using our any of our services/website you agree to these terms and that you will not hold the owner/creator of this website liable for any and all damages, legal and/or otherwise.</p>
  </div>

app/views/messages/_new.html.erb
<% @message = Message.new %>
<div class="row">
  <div class="col-md-6 col-centered">
    <h5>Interested in any of our services?</h5> 
    <h5>Have questions about what we do?</h5> 
    <h5>Don't hesitate to contact us!</h5>
    &nbsp;
    <%= form_for @message, url: create_message_url do |f| %>
      <%= notice %>
      <%= @message.errors.full_messages.join(', ') %>

      <%= f.text_field :name, placeholder: 'name' %>
      <%= f.email_field :email, placeholder: 'email' %>
      <%= f.text_area :content, placeholder: 'message' %>
      <%= f.submit 'Send' %>
    <% end %>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/_products-5.html.erb
    <div class="row">
      <div class="center">
        <h3 id="logo-three"><u>Website & SEO Improvement</u></h3>
      </div>
    </div>
    
    <div class="row">
      
      <div class="col-md-6">
          <ul>
            <strong><h4>SEO Analysis & Improvement:</h4></strong>
            <li><strong>Website Analysis:</strong> Free(up to 10 pages)</li>
            <li><strong>SEO Update(per page):</strong> $15</li>
            <li><strong>New SEO Implementation(per page):</strong> $20</li>
          </ul>
      </div>
      
      <div class="col-md-6">
          <ul>
            <strong><h4>Website Optimization:</h4></strong>
            <li><strong>Front end website changes:</strong> $45/hr</li>
            <li><strong>Back end website changes(Ruby on Rails only):</strong> $85/hr</li>
          </ul>
      </div> 
      
    </div>

app/views/static_pages/_products.html.erb
<div class="row">
  <div class="center">
        <h3 id="logo-three"><u>Social Media</u></h3>
  </div>
</div>

<div class="row">
      
      <div class="col-md-6">
          <ul>
            <h4>Social Media Account Creation</h4>
            <li><strong>1 account:</strong> $5</li>
            <li><strong>2 accounts:</strong> $9</li>
            <li><strong>3 accounts:</strong> $13</li>
            <li><strong>4 accounts:</strong> $15</li>
          </ul>
      </div>
        
      
      <div class="col-md-6">
          <ul>
            <h4>Social Media Account Curation(per account)</h4>
            <li><strong>1 week:</strong> $20</li>
            <li><strong>2 weeks:</strong> $38</li>
            <li><strong>3 weeks:</strong> $58</li>
            <li><strong>4 weeks:</strong> $78</li>
          </ul>
      </div> 
      
    </div>

app/views/static_pages/_serv1-5.html.erb
        <h4>What we do:</h4>
            <ul>
                <li><strong>Friendship?</strong> Only online.</li> 
                <li><strong>Hobbies?</strong> No.</li> 
                <li><strong>Tinder?</strong> My 45 Facebook accounts all have their own Tinder.</li>
                <li><strong>Alcohol?</strong> I haven't stopped drinking for 2 years, because of the stress of maintaining popularity on every existing social media platform for 45 different, imaginary people.
                <li><strong>Who am I?</strong> No idea at this point.</li> 
                <li><strong>What can I do for you?</strong> Fucking Social Media, thats what.</li>  
            </ul>
        &nbsp;

app/views/static_pages/_serv2-5.html.erb
<h4>SEO Analysis & Improvement includes:</h4>
        <ul>
            <li><strong>Preliminary SEO analysis for your full website</strong></li>
            <li><strong>Improvement of out dated SEO practices</strong></li>
            <li><strong>Implementation of current best SEO practices</strong></li>
            <li><strong>Creation of linked social media accounts</strong></li>
            <li><strong>Social media integration in order to create orgainc backlinks and website visits</strong></li>
        </ul>
        &nbsp;

app/views/static_pages/_serv2.html.erb
        <div class="center">
            <h3>
                <div><u>SEO Analysis & Improvement</u></div>
            </h3>
            <p>
                Not many people checking out your website? If you google it does it even come up? Well guess what motherfucker, we'll make it happen! Our team(literally just me) has been learing and implementing the best and most up to date SEO practices for years! 
            </p>
        </div>
    &nbsp;
        

app/views/static_pages/_serv3-5.html.erb
<h4>I code in all these languages/libraries!</h4>
        <ul>
            <li><strong>Ruby</strong></li>
            <li><strong>Ruby on Rails</strong>(I wrote this website in ROR)</li>
            <li><strong>HTML5</strong></li>
            <li><strong>CSS/SASS</strong></li>
            <li><strong>Bootstrap</strong></li>
            <li><strong>SQLite</strong></li>
            <li><strong>JQuery</strong></li>
        </ul>
    <div class="center">
        <p>
            I can make your website faster! Cooler looking! Slower! Better! Whatever you want your website to be I can do it! Cats everywhere? Done. A picture of your aunt making out with Ted Cruz on a buring airship? I've already photoshopped it and uploaded it to your website! It's done! Really, even if you want it to look shitty I'll set it up! Bam!
        </p>
        &nbsp;

app/views/static_pages/_serv4-5.html.erb
        <ul>
            <li><strong>Not enough Facebook friends?</strong> I'll make you seem more fun, post some engaging stuff, join like 16 Facebook groups and constantly start meaningful threads in them. You'll be so popular you won't ever have time for your real friends!</li>
            <li><strong>Want Instagram followers?</strong> I got you! Not only will I collect and analyze your Instagram data for you, I'll post in a consistent manner following engagment trends to maximize your likes and steadily gain followers.</li>
            <li><strong>Is that putting too much thought into social media?</strong> Only if you don't want to be good at it!</li>
            <li><strong>Guess what else?</strong> Linkedin: Done. Youtube: Super Done. Literally every form of social media: Done. Anything I don't know: I'll learn it, implement best practices, and make your account successful! I'll even make the accounts!</li>
        </ul>
    &nbsp;

app/views/static_pages/_serv4.html.erb
        <div class="center">
            <h3>
                <div><u>Social Media Curation</u></div>
            </h3>
            <p>
                Want more Instagram followers? More Facebook friends? I got you. Besides writing code alone in my one room apt, curating my 45 individual social media personalities is literally the only thing that makes me believe for a second that I have friends. And thats why I'm so good at it.
            </p>
        </div>
        

app/views/static_pages/_services_mobile.html.erb
<div clas="col-md-6">
    <div class="center">
        &nbsp;
        
        <h3>
            <div id="social"><u>Social Media Profile Creation</u></div>
        </h3>
        <p>
            We're professionsals when it comes to social media. At Social Curation, each of our staff members are required to not only create new social media accounts on all popular platforms in addition to their already existing accounts, but maintain these accounts using the latest best social media practices. If you need an account update, new personal account, or fake account* you can be sure that you're in the best hands. We literally do nothing but practice SEO and social media growth strategies in our spare time. 
        </p>
    </div>
    &nbsp;
        <h4>What we do:</h4>
            <ul>
                <li><strong>Friendship?</strong> Only online.</li> 
                <li><strong>Hobbies?</strong> No.</li> 
                <li><strong>Tinder?</strong> My 45 Facebook accounts all have their own Tinder.</li>
                <li><strong>Alcohol?</strong> I haven't stopped drinking for 2 years, because of the stress of maintaining popularity on every existing social media platform for 45 different, imaginary people.
                <li><strong>Who am I?</strong> No idea at this point.</li> 
                <li><strong>What can I do for you?</strong> Fucking Social Media, thats what.</li>  
            </ul>
        &nbsp;
        
    <div class="center">
        <h3>
            <div id="SEO"><u>SEO Analysis & Improvement</u></div>
        </h3>
        <p>
            Not many people checking out your website? If you google it does it even come up? Well guess what motherfucker, we'll make it happen! Our team(literally just me) has been learing and implementing the best and most up to date SEO practices for years! 
        </p>
    </div>
    &nbsp;
        <h4>SEO Analysis & Improvement includes:</h4>
        <ul>
            <li><strong>Preliminary SEO analysis for your full website</strong></li>
            <li><strong>Improvement of out dated SEO practices</strong></li>
            <li><strong>Implementation of current best SEO practices</strong></li>
            <li><strong>Creation of linked social media accounts</strong></li>
            <li><strong>Social media integration in order to create orgainc backlinks and website visits</strong></li>
        </ul>
        &nbsp;

    <div class="center">
        <h3>
            <div id="website"><u>Website Optimization</u></div>
        </h3>
        <p>
            Is your website boring? Is your website out of date? Does it just not have that modern moving shit with a simplistic design and intuitive menu feel that you've grown so accustom to seeing on every hip website for a startup coming out of silicon valley? Do you just not want to have to pay to remove that annoying "wix.com" from the footer of your Wix website? Well have I got good news for you!
        </p>
    </div>
    &nbsp;
        <h4>I code in all these languages/libraries!</h4>
        <ul>
            <li><strong>Ruby</strong></li>
            <li><strong>Ruby on Rails</strong>(I wrote this website in ROR)</li>
            <li><strong>HTML</strong></li>
            <li><strong>CSS/SASS</strong></li>
            <li><strong>Bootstrap</strong></li>
            <li><strong>SQLite</strong></li>
            <li><strong>Javascript</strong></li>
            <li><strong>React</strong></li>
        </ul>
    <div class="center">
        <p>
            I can make your website faster! Cooler looking! Slower! Better! Whatever you want your website to be I can do it! Cats everywhere? Done. A picture of your aunt making out with Ted Cruz on a buring airship? I've already photoshopped it and uploaded it to your website! It's done! Really, even if you want it to look shitty I'll set it up! Bam!
        </p>
        &nbsp;
        
        <h3>
            <div id="social-med"><u>Social Media Curation</u></div>
        </h3>
        <p>
            Want more Instagram followers? More Facebook friends? I got you. Besides writing code alone in my one room apt, curating my 45 individual social media personalities is literally the only thing that makes me believe for a second that I have friends. And thats why I'm so good at it.
        </p>
    </div>
        <ul>
            <li><strong>Not enough Facebook friends?</strong> I'll make you seem more fun, post some engaging stuff, join like 16 Facebook groups and constantly start meaningful threads in them. You'll be so popular you won't ever have time for your real friends!</li>
            <li><strong>Want Instagram followers?</strong> I got you! Not only will I collect and analyze your Instagram data for you, I'll post in a consistent manner following engagment trends to maximize your likes and steadily gain followers.</li>
            <li><strong>Is that putting too much thought into social media?</strong> Only if you don't want to be good at it!</li>
            <li><strong>Guess what else?</strong> Linkedin: Done. Youtube: Super Done. Literally every form of social media: Done. Anything I don't know: I'll learn it, implement best practices, and make your account successful! I'll even make the accounts!</li>
        </ul>
    &nbsp;
    &nbsp;
    <p class="tiny">*Fake accounts will not be made to impersonate existing people. Fake accounts may not be used to harrass anyone in any way. Failure to comply with these rules and all rules outlined in our contracts and/or about page will result in termination of your service(s) and/or contract(s). By using our any of our services/website you agree to these terms and that you will not hold the owner/creator of this website liable for any and all damages, legal and/or otherwise.</p>
</div>

app/views/static_pages/_slide.html.erb
<div class="center">
        <div class="flexslider">
                <ul class="slides">
                        <li>
                                <%= link_to image_tag('christine-fb.png'), root_path(:anchor=> "social") %>
                                <h1><%= link_to "Social Media Profile Creation", root_path(:anchor=> "social") %></h1>
                        </li>
                        <li>
                                <%= link_to image_tag('SEO-bkg.jpg'), root_path(:anchor=> "SEO") %>
                                <h1><%= link_to "SEO Analysis & Improvement", root_path(:anchor=> "SEO") %></h1>
                        </li>
                        <li>
                                <%= link_to image_tag('Website-image.jpg'), root_path(:anchor=> "website") %>
                                <h1><%= link_to "Website Optimization", root_path(:anchor=> "website") %></h1>
                        </li>
                        <li>
                                <%= link_to image_tag('social-media.jpg'), root_path(:anchor=> "social-med") %>
                                <h1><%= link_to "Social Media Curation", root_path(:anchor=> "social-med") %></h1>
                        </li>
                </ul>
        </div>
</div>

app/views/static_pages/home.html+phone.erb
<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;">

<div id="logo-phone">
    Social Curation
</div>

&nbsp;

<div class="slider">
<div id="slide-menu">
  <div class="bcg">
    <div class="phone-logo center"><span>
      <a>Services</a>
    </span></div>
  </div>
</div>

&nbsp;

<div class="hidden-div">
        <%= render 'services_mobile' %>
</div>
</div>

&nbsp;

<div class="slider">
<div id="slide-menu">
  <div class="bcg">
    <div class="phone-logo center"><span>
      <a>Pricing</a>
    </span></div>
  </div>
</div>

&nbsp;

<div class="hidden-div">
        <%= render 'products' %>
      &nbsp;
        <%= render 'products-5' %>
</div>
</div>

&nbsp;


        <div class="center">
          <%= render 'messages/new' %>
        </div>

</div>

</meta>

app/views/static_pages/home.html.erb
<div id="head-slide">
  <div class="bcg">

        <div id="logo">
          <span>
            <u>Social Curation</u>
          </span>
        </div>
        
        <div id="logo-two">
          <span>
            Social Media Optimization | SEO | Full Service Web Development
          </span>
        </div>
        
<%= render 'slide' %>
  
  

<div id="slide-menu">
  <div class="bcg">
    <h1><span>
      Services
    </span></h1>
  </div>
</div>

</div>
</div>



<div id="slide-bcg">
  <div class="bcg" id="social">
      
    <div class="container-fluid">
    <div class="row">
        <div class="col-lg-6">
          
          <div clas="slide-test">
            <div class="bcg">
              <div id="slides-padded">
                <%= render 'serv1' %>
              </div>
            </div>
          </div>
          
        </div>
        <div class="col-lg-6">
          
          <div id="slide-test">
            <div class="bcg">
              <div id="slides-padded">
                <%= render 'serv1-5' %>
              </div>
            </div>
          </div>
          
        </div>
    </div>
</div>


</div>
</div>


<div id="slide-bcg">
  <div class="bcg" id="SEO">
    
    <div class="container-fluid">
    <div class="row">
        <div class="col-lg-6">
          
          <div class="slide-test">
            <div class="bcg">
              <div id="slides-padded">
                <%= render 'serv2-5' %>
              </div>
            </div>
          </div>
          
        </div>
        <div class="col-lg-6">
          
          <div class="slide-test">
            <div class="bcg">
              <div id="slides-padded">
                <%= render 'serv2' %>
              </div>
            </div>
          </div>
          
        </div>
    </div>
</div>

</div>
</div>

<div id="slide-bcg">
  <div class="bcg" id="website">
    
    <div class="container-fluid">
    <div class="row">
        <div class="col-lg-6">
          
          <div class="slide-test">
            <div class="bcg">
              <div id="slides-padded">
                <%= render 'serv3' %>
              </div>
            </div>
          </div>
          
        </div>
        <div class="col-lg-6">
          
          <div class="slide-test">
            <div class="bcg">
              <div id="slides-padded">
                <%= render 'serv3-5' %>
              </div>
            </div>
          </div>
          
        </div>
    </div>
</div>

</div>
</div>

<div id="slide-bcg">
  <div class="bcg" id="social-med">
    
    <div class="container-fluid">
    <div class="row">
        <div class="col-lg-6">
          
          <div class="slide-test">
            <div class="bcg">
              <div id="slides-padded">
                <%= render 'serv4-5' %>
              </div>
            </div>
          </div>
          
        </div>
        <div class="col-lg-6">
          
          <div class="slide-test">
            <div class="bcg">
              <div id="slides-padded">
                <%= render 'serv4' %>
              </div>
            </div>
          </div>
          
        </div>
    </div>
</div>

</div>
</div>

<div id="slide-bcg-s">
  <div class="bcg">
    <%= image_tag 'swoop.png', style: 'width:100%;' %>
  </div>
</div>


<div id="slide-bcg-bottom">
  <div class="bcg">

<div class="slider">
<div id="slide-menu">
  <div class="bcg">
    <h1 class="pricing"><span>
      <a>Pricing</a>
    </span></h1>
  </div>
</div>


<div class="hidden-div">
<div class="container">
<div class="slide-test-bottom">
  <div class="bcg">
    <div id="slides-padded">
      &nbsp;
        <%= render 'products' %>
    </div>
  </div>
</div>
</div>

<div class="slide-bcg-bottom">
  <div class="bcg">
  </div>
</div>

<div class="container">
<div class="slide-test-bottom">
  <div class="bcg">
    <div id="slides-padded">
      &nbsp;
        <%= render 'products-5' %>
    </div>
  </div>
</div>
</div>
</div>

</div>

<div id="slide-bcg-bottom">
  <div class="bcg">
  </div>
</div>

<div>
<div id="slide-menu">
  <div class="bcg">
    <h1><span>
      Contact Us
    </span></h1>
  </div>
</div>

<div class="div">   
    <div class="container">
      <div id="slide-test-bottom">
        <div class="bcg">
          <div id="slides-padded">
          &nbsp;
          <%= render 'messages/new' %>
          </div>
        </div>
      </div>
    </div>
</div> 

</div>

<div id="slide-bcg-bottom">
  <div class="bcg">
  </div>
</div>

</div>
</div>

app/views/static_pages/test.html.erb
<div clas="row">
<div class="col-md-6 col-centered">
<div class="colored" id="div1" onclick="setColor(this)"></div>
<div class="colored" id="div2" onclick="setColor(this)"></div>
<div class="colored" id="div3" onclick="setColor(this)"></div>
<div class="colored" id="div4" onclick="setColor(this)"></div>
</div>
</div>

<div clas="row">

<div class="colored" id="div5" onclick="setColor(this)"></div>
<div class="colored" id="div6" onclick="setColor(this)"></div>
<div class="colored" id="div7" onclick="setColor(this)"></div>
<div class="colored" id="div8" onclick="setColor(this)"></div>

</div>

<button onclick="buttonCheck()">Try it</button>
<h1 id="demo"></h1>